common.o: common.cpp include/common.hpp include/dmerror.hpp
confReader.o: confReader.cpp include/confReader.hpp include/common.hpp \
  include/logger.hpp include/dmerror.hpp include/common.hpp
datamanager.o: datamanager.cpp include/datamanager.hpp \
  include/MailBox.hpp include/common.hpp include/common.hpp \
  include/confReader.hpp include/dmerror.hpp include/stapdebug.hpp \
  include/logger.hpp include/subscriptionMgr.hpp include/datamanager.hpp \
  include/MailBox.hpp
dmerror.o: dmerror.cpp include/dmerror.hpp
logger.o: logger.cpp include/logger.hpp
MailBox.o: MailBox.cpp include/stapdebug.hpp include/MailBox.hpp \
  include/common.hpp include/confReader.hpp include/dmerror.hpp \
  include/common.hpp include/logger.hpp include/datamanager.hpp
subscriptionMgr.o: subscriptionMgr.cpp include/subscriptionMgr.hpp \
  include/datamanager.hpp include/MailBox.hpp include/common.hpp \
  include/datamanager.hpp include/stapdebug.hpp include/dmerror.hpp \
  include/MailBox.hpp include/common.hpp include/logger.hpp \
  include/confReader.hpp
