# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  push:
    branches: 
      - 'master'
      - 'stable-*'
  pull_request:
    branches: 
     - 'master'
     - 'stable-*'
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    uses: eclipse/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: tools.linuxtools
      javaVersion: 21
    secrets:
      gitlabAPIToken: ${{ secrets.LINUXTOOLS_GITLAB_API_TOKEN }}